---

- name: Pin current kernel version
  hosts: pve_nodes
  tasks:
    - name: Pin the current kernel version
      ansible.builtin.command: "proxmox-boot-tool kernel pin 6.8.12-8-pve"
      changed_when: true
      notify: Refresh boot configuration
  handlers:
    - name: Refresh boot configuration
      ansible.builtin.command: proxmox-boot-tool refresh
      changed_when: true

- name: Pin network interface names
  hosts: pve_0
  vars:
    interfaces:
      - name: enxg0
        mac: 58:47:ca:7b:b7:26
      - name: enxg1
        mac: 58:47:ca:7b:b7:27
      - name: en2g0
        mac: 58:47:ca:7b:b7:28
      - name: en2g1
        mac: 58:47:ca:7b:b7:29
  roles:
    - networking

- name: Setup LINSTOR storage
  hosts: pve_nodes
  roles:
    - linstor
