---

- name: Pin current kernel version
  hosts: pve_nodes
  tasks:
    - name: Pin the current kernel version
      ansible.builtin.command: "proxmox-boot-tool kernel pin 6.8.12-8-pve"
      changed_when: true
      notify: Refresh boot configuration
  handlers:
    - name: Refresh boot configuration
      ansible.builtin.command: proxmox-boot-tool refresh
      changed_when: true

- name: Setup LINSTOR storage
  hosts: pve_nodes
  # remote_user: root
  roles:
    - linstor

- name: Start LINSTOR
  hosts: pve_0
  tasks:
    - name: Enable LINSTOR satellite service on all nodes
      ansible.builtin.systemd_service:
        name: linstor-satellite
        state: started
        enabled: true

    - name: Enable LINSTOR controller service on one node only
      ansible.builtin.systemd_service:
        name: linstor-controller
        state: started
        enabled: true
