---

- name: Pin current kernel version
  hosts: pve_nodes
  vars:
    PVE_KERNEL_VERSION: 6.17.2-2-pve
  tasks:
    - name: Pin the current kernel version
      ansible.builtin.command: "proxmox-boot-tool kernel pin {{ PVE_KERNEL_VERSION }}"
      changed_when: true
      notify: Refresh boot configuration
  handlers:
    - name: Refresh boot configuration
      ansible.builtin.command: proxmox-boot-tool refresh
      changed_when: true

- name: Setup networking
  hosts: pve_nodes
  tags:
    - setup
    - networking
  roles:
    - networking

- name: Setup Intel SR-IOV
  hosts: pve_nodes
  tags:
    - setup
    - intel_sriov
  roles:
    - intel_sriov

- name: Setup LINSTOR storage
  hosts: pve_nodes
  tags:
    - setup
    - linstor
  roles:
    - linstor
