---
- name: Setup PVE
  hosts: pve_nodes
  tags:
    - setup
    - pve_conf
  roles:
    - pve_conf

- name: Setup LINSTOR storage
  hosts: pve_nodes
  tags:
    - setup
    - linstor
  roles:
    - linstor
