#SPDX-License-Identifier: MIT-0
---
# handlers file for linstor

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: (Re)Start LINSTOR satellite service
  ansible.builtin.systemd_service:
    name: linstor-satellite
    state: restarted
    enabled: true

- name: (Re)Start DRBD Reactor service
  ansible.builtin.systemd_service:
    name: drbd-reactor
    state: restarted
    enabled: true

- name: (Re)Start DRBD Reactor Reload service
  ansible.builtin.systemd_service:
    name: drbd-reactor-reload.path
    state: restarted
    enabled: true
