global:
  domain: argocd.homelab.fouad.dev
  image:
    repository: quay.io/argoproj/argocd
    tag: v3.3.9

configs:
  params:
    server.insecure: true

controller:
  replicas: 3

repoServer:
  replicas: 3

applicationSet:
  replicas: 3

server:
  replicas: 3
  ingress:
    enabled: true
    ingressClassName: traefik
