version: '3.8'

volumes:
  portainerVol:
    driver: linbit/linstor-docker-volume
    driver_opts:
      replicas: "1"
      size: "200M"

services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainerVol:/data
