---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: scw-sm
  target:
    name: sonarr
  refreshInterval: 60s
  dataFrom:
    - extract:
        key: path:/arr-apps/sonarr
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
