base-app:
  image:
    repository: maintainerr/maintainerr
    tag: 3.12.0
  service:
    port: 6246
  ingressRoute:
    enabled: true
  pvc:
    enabled: true
    size: 500Mi
    mountPath: /opt/data
    # cloneFromNfsPath: /mnt/user/appdata/maintainerr
  containerSecurityContext:
    readOnlyRootFilesystem: false
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 1024Mi
