extraPatch:
  spec:
    source:
      repoURL: ghcr.io/seerr-team/seerr
      chart: seerr-chart
      targetRevision: 3.9.1
      helm:
        releaseName: seerr
        valuesObject:
          nameOverride: seerr
          image:
            registry: ghcr.io
            repository: seerr-team/seerr
            # -- Overrides the image tag whose default is the chart appVersion.
            tag: "v3.3.0"

          config:
            persistence:
              name: seerr-data
              # -- Size of persistent disk
              size: 1Gi
              # -- Access modes of persistent disk
              accessModes:
                - ReadWriteOnce
              # -- Storage class for the PVC. Set to "-" to disable dynamic provisioning. Uses default storage class if no value is provided
              storageClass: linstor-replicated
              annotations:
                argocd.argoproj.io/sync-options: "Delete=false"
                argocd.argoproj.io/sync-wave: "-1"

          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 4000m
              memory: 1024Mi
