---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: librechat-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: scw-sm
  target:
    name: librechat-credentials
  refreshInterval: 60s
  dataFrom:
    - extract:
        key: path:/libre-chat/credentials
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
