---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr-automated
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: scw-sm
  target:
    name: radarr-automated
  refreshInterval: 60s
  dataFrom:
    - extract:
        key: path:/arr-apps/radarr-automated
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
