scw-sm-secret:
    access-key: ENC[AES256_GCM,data:6tOFW6RV36dFtcdNZ13LVniZdig=,iv:boC5r0VWiibOIe/98BKPWULAIqdbOohdj5MjbbOVrqs=,tag:Ibh2FbehZ3wIMIzq0PnXSw==,type:str]
    secret-key: ENC[AES256_GCM,data:bWZkDxDpWrG3xRTZ0bESr60IK95b7W+QQ1anPtnUfRcXurl0,iv:cFQH91v2yegyS2vrfJzGiP8K1HQclSkItJs0iSJgsqY=,tag:12BTL85c10U/JI/jLqcRZw==,type:str]
scw-linstor-remote-secret:
    access-key: ENC[AES256_GCM,data:XWmSO25ndVv760Hi+iUOHFjd3Vs=,iv:b/+IXfPdDNdHYVXfY7TOatjCrqMuUVC1tP3CJdJobUA=,tag:Un30CJqw/d1U6vLE8QCcPg==,type:str]
    secret-key: ENC[AES256_GCM,data:tYwAGJ0/sV+98pM+pT5ZmZx7CshhFGh2di9giGX31mhwW9iG,iv:3AwgyF/vgAl0RVbByAbv8frwgxH/wxrkzI8eg2gKCd8=,tag:q4d7XHNaW4K6qzMIlVlxtw==,type:str]
argocd:
    admin-password: ENC[AES256_GCM,data:DSNoMnP5/h2iqo5ZgRZuEArbxcs/h53LZ3CePAQJ0aA=,iv:7I1sde2bi15A/WP1YZfEgIDslChIV8vWA1K/6wMW3hQ=,tag:EidwU+Y/9t7Rl12t3rQsIA==,type:str]
    server-secretkey: ENC[AES256_GCM,data:fg3+pwO2BxSxwUh9y/kfvtCHkrvQT8kMwqk2eLVRnia+yib4uz4/nWuXnms=,iv:jk+XAEDj1wfwN0n4cWKfdbsDC+NVArr2TpWBD5YVGFQ=,tag:1ihbOFnglgaRipOjX0xLmg==,type:str]
github-webhooks:
    secret: ENC[AES256_GCM,data:8xLneSxrHixKGe1tqdVyUIdt1dDMxGOcoJ0OiwUvEV0=,iv:hxHVgqivmGO9KVi/HMDx6PcuP/92MG8Z8tYT/M432zw=,tag:VTWpLmny4pLPlt7sKWYovA==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAUKdru6HNRCwDpm6YCZSBjTndpVuxmoOL3YwLMy2baS
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE1GQWFOQSBPMFl6
            Vm5DeFJEaUFwVWUxWnJuVTVaUHdGNFUxa1lhdHh5eWxOVVFqeW4wCnJpTDlmL3RD
            RlNOa2Y3QnJnUXkyRitQRWx1ajRWb1RocHNzSXpJZklCMXcKLS0tIDBPTWZ5ZVBG
            K3JpajZMNlFzZm1xK1czT3BJc1ZFbUdlTTROSTRPVHNkWmMKN80qwTywAJTZvfHN
            8oX1mTR7GEgnKg3FslNZMQMY6KLSPTWSB6saZNR/+ulC9RxcppSRKmjAcEZWA9Q+
            KAY2EQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T20:47:08Z"
    mac: ENC[AES256_GCM,data:VDpBFbTZzo0/4L5d0fW83LRT2mHJFybM5NByaMwov9Bwr+c6OOsWH0ew+CfPoK58lXYiW2NHpOCLoypuIo1tDFOPNfwBFRbrmav2mCsi/OKlUGOwe6cj8UzrzReArh27ao7SU2ug1pwsJqC2NZ5TPj26oydUVCe5K8obx/ts4Cc=,iv:TyQW2YhyPPsNCEqTI1o6knu1qVqIfowpR3adi8aL1D4=,tag:ecdEE6WAJWTCsznsI01VDw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
