scw-sm-secret:
    access-key: ENC[AES256_GCM,data:6tOFW6RV36dFtcdNZ13LVniZdig=,iv:boC5r0VWiibOIe/98BKPWULAIqdbOohdj5MjbbOVrqs=,tag:Ibh2FbehZ3wIMIzq0PnXSw==,type:str]
    secret-key: ENC[AES256_GCM,data:bWZkDxDpWrG3xRTZ0bESr60IK95b7W+QQ1anPtnUfRcXurl0,iv:cFQH91v2yegyS2vrfJzGiP8K1HQclSkItJs0iSJgsqY=,tag:12BTL85c10U/JI/jLqcRZw==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAUKdru6HNRCwDpm6YCZSBjTndpVuxmoOL3YwLMy2baS
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE1GQWFOQSBPMFl6
            Vm5DeFJEaUFwVWUxWnJuVTVaUHdGNFUxa1lhdHh5eWxOVVFqeW4wCnJpTDlmL3RD
            RlNOa2Y3QnJnUXkyRitQRWx1ajRWb1RocHNzSXpJZklCMXcKLS0tIDBPTWZ5ZVBG
            K3JpajZMNlFzZm1xK1czT3BJc1ZFbUdlTTROSTRPVHNkWmMKN80qwTywAJTZvfHN
            8oX1mTR7GEgnKg3FslNZMQMY6KLSPTWSB6saZNR/+ulC9RxcppSRKmjAcEZWA9Q+
            KAY2EQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T16:38:06Z"
    mac: ENC[AES256_GCM,data:bUyHKEFiZScQoYdiBDDtpV6RRzuoOdjvC99BgMO/IHe5U24GSaWjm2xUcE2bOYJofMz6iGPcXZQ7WNaQZf6zTaN6nMO+vKXddogdV9XPAKAHCUtJPgDjnO6iUBN/Xtv0oM4Txi9CsoVFxdlL/A9P+B7FhlRNm7fnY/nD0PE6vKQ=,iv:869NAxqHyIZRItIH3Acp5hlUhjobrzJqth2Yn3Hp9r8=,tag:1K05SiP6z+ZY0SEVgvn4TA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
