scw-sm-secret:
    access-key: ENC[AES256_GCM,data:6tOFW6RV36dFtcdNZ13LVniZdig=,iv:boC5r0VWiibOIe/98BKPWULAIqdbOohdj5MjbbOVrqs=,tag:Ibh2FbehZ3wIMIzq0PnXSw==,type:str]
    secret-key: ENC[AES256_GCM,data:bWZkDxDpWrG3xRTZ0bESr60IK95b7W+QQ1anPtnUfRcXurl0,iv:cFQH91v2yegyS2vrfJzGiP8K1HQclSkItJs0iSJgsqY=,tag:12BTL85c10U/JI/jLqcRZw==,type:str]
argocd:
    admin-password: ENC[AES256_GCM,data:DSNoMnP5/h2iqo5ZgRZuEArbxcs/h53LZ3CePAQJ0aA=,iv:7I1sde2bi15A/WP1YZfEgIDslChIV8vWA1K/6wMW3hQ=,tag:EidwU+Y/9t7Rl12t3rQsIA==,type:str]
    server-secretkey: ENC[AES256_GCM,data:fg3+pwO2BxSxwUh9y/kfvtCHkrvQT8kMwqk2eLVRnia+yib4uz4/nWuXnms=,iv:jk+XAEDj1wfwN0n4cWKfdbsDC+NVArr2TpWBD5YVGFQ=,tag:1ihbOFnglgaRipOjX0xLmg==,type:str]
github-webhooks:
    pull-requests: ENC[AES256_GCM,data:N+0ISCn8GEN0FQjmg3RDZDFR5wrMPaRHhaHTsdem14Y=,iv:kZtmnxGEEhGZWy0FdC1YXHIlb27B0TKpMiPLxNtPSBI=,tag:+GsrGD8W8n6MzetN8LRj0g==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAUKdru6HNRCwDpm6YCZSBjTndpVuxmoOL3YwLMy2baS
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE1GQWFOQSBPMFl6
            Vm5DeFJEaUFwVWUxWnJuVTVaUHdGNFUxa1lhdHh5eWxOVVFqeW4wCnJpTDlmL3RD
            RlNOa2Y3QnJnUXkyRitQRWx1ajRWb1RocHNzSXpJZklCMXcKLS0tIDBPTWZ5ZVBG
            K3JpajZMNlFzZm1xK1czT3BJc1ZFbUdlTTROSTRPVHNkWmMKN80qwTywAJTZvfHN
            8oX1mTR7GEgnKg3FslNZMQMY6KLSPTWSB6saZNR/+ulC9RxcppSRKmjAcEZWA9Q+
            KAY2EQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T16:21:49Z"
    mac: ENC[AES256_GCM,data:SDFd46FGu7pZ4ZEqShRznVJ9HuKbek2bFsC9lsfyFieEZyh1giTI9YbHu/p/toDSHNtDFn87zAHbtpCdt4Spgfy1qAyxMSkAgdnjEcuQdWfKhZrksSj2hQpxyVN1xTIF9a/Y0jYcwK0sb+2o6gyVVtLjs+xqL6DlYPFN1vnWkkY=,iv:38Q+JQvbeioe6RLlLGWmEDK/LAhFFZiWMhUYDiI60ko=,tag:MrNshnmkaZv+dCSVVEDeVw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
