#SPDX-License-Identifier: MIT-0
---
# handlers file for docker
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes
    
- name: Restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
