base-app:
  image:
    repository: homebridge/homebridge
    tag: "2026-04-20"
  service:
    port: 8581
  podSecurityContext: null
  containerSecurityContext: null
  hostNetwork: true
  ingressRoute:
    enabled: true
  pvc:
    enabled: true
    size: 1Gi
    mountPath: /homebridge
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 1024Mi
