apiVersion: batch/v1
kind: CronJob
metadata:
  name: recyclarr
spec:
  schedule: "0 9 * * *"
  timeZone: "Europe/Paris"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            fsGroup: 10001
            seccompProfile:
              type: RuntimeDefault
          containers:
          - name: recyclarr
            image: recyclarr/recyclarr:8.7.0
            imagePullPolicy: IfNotPresent
            securityContext:
              privileged: false
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
            command:
              - recyclarr
              - sync
            env:
              - name: TZ
                value: "Europe/Paris"
              - name: RECYCLARR_CONFIG_DIR
                value: "/config"
              - name: RECYCLARR_DATA_DIR
                value: "/data"
            volumeMounts:
              - name: data
                mountPath: /data
              - name: config
                mountPath: /config
              - name: recyclarr-config
                mountPath: /config/recyclarr.yml
                subPath: recyclarr.yml
              - name: recyclarr-includes
                mountPath: /config/includes
              - name: secret-sonarr
                readOnly: true
                mountPath: "/run/secrets/sonarr"
              - name: secret-sonarr-4k
                readOnly: true
                mountPath: "/run/secrets/sonarr-4k"
              - name: secret-radarr-requests
                readOnly: true
                mountPath: "/run/secrets/radarr-requests"
              - name: secret-radarr-automated
                readOnly: true
                mountPath: "/run/secrets/radarr-automated"
              - name: secret-radarr-4k
                readOnly: true
                mountPath: "/run/secrets/radarr-4k"
          volumes:
          - name: config
            emptyDir: {}
          - name: data
            emptyDir: {}
          - name: recyclarr-config
            configMap:
              name: recyclarr-config
          - name: recyclarr-includes
            configMap:
              name: recyclarr-includes
          - name: secret-sonarr
            secret:
              secretName: sonarr
          - name: secret-sonarr-4k
            secret:
              secretName: sonarr-4k
          - name: secret-radarr-requests
            secret:
              secretName: radarr-requests
          - name: secret-radarr-automated
            secret:
              secretName: radarr-automated
          - name: secret-radarr-4k
            secret:
              secretName: radarr-4k
