apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cronjob.yaml

configMapGenerator:
- name: recyclarr-config
  options:
    disableNameSuffixHash: true
  files:
    - assets/recyclarr.yml
    - assets/includes/sonarr-main.yml
    - assets/includes/sonarr-4k.yml
    - assets/includes/radarr-automated.yml
    - assets/includes/radarr-requests.yml
    - assets/includes/radarr-4k.yml