apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cronjob.yaml

configMapGenerator:
- name: recyclarr-config
  behavior: merge
  options:
    disableNameSuffixHash: true
  files:
    - recyclarr.yml
    - includes/sonarr-main.yml
    - includes/sonarr-4k.yml
    - includes/radarr-automated.yml
    - includes/radarr-requests.yml
    - includes/radarr-4k.yml