global:
  domain: argocd.homelab.fouad.dev

configs:
  params:
    server.insecure: true

redis-ha:
  enabled: true

controller:
  replicas: 3

repoServer:
  replicas: 3

applicationSet:
  replicas: 3

server:
  replicas: 3
  ingress:
    enabled: true
    ingressClassName: traefik
