name: 'Cloudflare'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *' # Every day, at 9 AM

permissions:
  contents: read

jobs:
  adblock_terraform:
    name: 'Adblock - Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: cloudflare/ad_block

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
