{{- if .Values.pvc.cloneFromNfsPath }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "base-app.name" . }}-clone-nfs-data
  labels:
    {{- include "base-app.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 1  # Fail fast if issues
  template:
    metadata:
      name: {{ include "base-app.name" . }}-clone-nfs-data
      labels:
        {{- include "base-app.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: pre-install-job
          image: alpine:latest
          command:
            - /bin/sh
            - -c
            - |
              apk add --no-cache rsync nfs-utils
              mkdir -p /nfs /linstor
              # Initial sync (mounts handle rest)
              rsync -avz --ignore-existing /nfs/ /linstor/
              echo "Migration complete"
          volumeMounts:
            - mountPath: /nfs
              name: source-nfs
            - mountPath: /linstor
              name: target-linstor
          # securityContext:
          #   privileged: true  # For NFS mount if needed
      volumes:
        - name: source-nfs
          nfs:
            server: 192.168.200.10
            path: {{ .Values.pvc.cloneFromNfsPath }}
            readOnly: true
        - name: target-linstor
          persistentVolumeClaim:
            claimName: {{ include "base-app.name" . }}-{{ .Values.pvc.name }}
{{- end }}