---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "base-app.name" . }}
  labels:
    {{- include "base-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- with .Values.updateStrategy }}
  strategy:
    type: {{ .type }}
    {{- with .rollingUpdate }}
    rollingUpdate:
      maxUnavailable: {{ .maxUnavailable }}
      maxSurge: {{ .maxSurge }}
    {{- end }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "base-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "base-app.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.hostNetwork }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          image: "{{ required "A valid image.repository is required!" .Values.image.repository }}:{{ required "A valid image.tag is required!" .Values.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if or .Values.env .Values.secrets.env }}
          env:
            {{- include "base-app.envFromValues" . | indent 12 }}
            {{- include "base-app.envFromSecrets" . | indent 12 }}
          {{- end }}
          {{- with .Values.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with (required "Please set resources R/L" .Values.resources) }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.pvc.enabled .Values.volumeMounts }}
          volumeMounts:
            {{- if .Values.pvc.enabled }}
            - mountPath: {{ .Values.pvc.mountPath }}
              name: {{ .Values.pvc.name }}
            {{- end }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
      {{- if or .Values.pvc.enabled .Values.volumes }}
      volumes:
        {{- if .Values.pvc.enabled }}
        - name: {{ .Values.pvc.name }}
          persistentVolumeClaim:
            claimName: {{ include "base-app.name" . }}-{{ .Values.pvc.name }}
        {{- end }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              {{- include "base-app.selectorLabels" . | nindent 14 }}
