{{- range $name, $secret := .Values.secrets.env }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-%s" (include "base-app.name" $) $name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: scw-sm
  target:
    name: {{ printf "%s-%s" (include "base-app.name" $) $name }}
  refreshInterval: {{ $secret.refreshInterval | default "60s" }}
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: {{ required "secrets.env.*.remoteRef.key is required" $secret.remoteRef.key }}
{{- end }}