{{- if .Values.pvc.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "base-app.name" . }}-{{ .Values.pvc.name }}
  labels:
    app.kubernetes.io/name: {{ include "base-app.name" . }}
    app.kubernetes.io/instance: {{ include "base-app.name" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: Delete=false
spec:
  storageClassName: linstor-replicated
  accessModes: {{ .Values.pvc.accessModes }}
  resources:
    requests:
      storage: {{ required "A valid pvc.size is required!" .Values.pvc.size }}
{{- end }}